### ISSUE TITLE
card-list 컴포넌트 구현

### ISSUE THREAD

**Issue by SihyeonHong** [fesi-05-01/frontend#30]
### Description
card-list 컴포넌트 구현 (모임 찾기, 찜한 모임 페이지에서 사용)

### Tasks
- [x] join now 버튼
- [x] closed 버튼
- [x] 개설확정
- [x] 인원수 표기 
- [x] 하트 버튼
- [x] 기본 레이아웃 및 디자인
- [x] default / hover / disabled 
- [x] props로 데이터 받기 
- [x] 이 모든 걸 card-small에서 한 번 더 
- [x] 아 마감됐을 때 바뀌는 거 안 했다
- [x] 아 맞다 반응형
