### ISSUE TITLE
모임 찾기 페이지 컨테이너 

### ISSUE THREAD

**Issue by SihyeonHong** [fesi-05-01/frontend#44]
### Description
모임 찾기 페이지의 전체 컨테이너 레이아웃 작업 

### Tasks
- [x] 지금 모임에 참여해보세요 
- [x] 그 아래의 커다란 컨테이너
- [x] 달램핏 / 위케이션과 그 밑에 공통 컴포넌트 들어갈 컨테이너 
- [x] 지역과 날짜 필터링하는 부분
- [x] 그 밑에 카드 리스트 
- [x] 반응형 레이아웃
- [x] 아 그 필터도 반응형
